### ISSUE TITLE
In Program.Main the statement await stub.SignalAsync("signal-name", "Sally"); incorrect

### ISSUE THREAD

**Issue by Yuriy-Paramonov** [nforgeio/cadence-samples#1]
await stub.SignalAsync("signal-name", "Sally"); has to be updated to: 
await stub.SignalAsync("signal", "Sally");

The issue is located at line 105; file Program.cs; project: hello-signal.

**Comment by jefflill** [comment]
Thanks, good catch.  I just pushed this change.
